dist: trusty
language: python
cache: pip
python:
    - "3.6"
before_install:
    - sudo apt-get -y update
    - sudo apt-get -y install python3-pip python3-dev debhelper devscripts debhelper devscripts p7zip-full libssl-dev dpkg-dev build-essential libjpeg-dev libtiff-dev libsdl1.2-dev libnotify-dev freeglut3 ibus-gtk3 xvfb
    # - sudo apt-get -y install libwebkit2gtk-4.0
    - sudo apt-get -y install libwebkitgtk-3.0
install:
    - pip install pipenv
    - pipenv run pip install wxpython==4.0.2 -v
    - pipenv update --dev
script:
    - LD_LIBRARY_PATH=$(pipenv --venv)/lib/python3.6/site-packages/wx xvfb-run pipenv run fab test
