version: 2.1.0.xxx.{build}
init:
- cmd: py -m pip install pipenv
environment:
  PY_PYTHON: 3.6-32
  PYTHONIOENCODING: utf_8
install:
- cmd: >-
    py -m pipenv update --dev
build_script:
- cmd: >-
    py -m pipenv run fab win:0,1,0
test_script:
- cmd: >-
    py -m pipenv run fab test:"-s"
artifacts:
- path: build\*\windows\*.zip
  name: zip
- path: build\*\windows\*.7z
  name: 7z
cache:
  - C:\Users\appveyor\.virtualenvs\outwiker-NhIuapJ3
