---
- name: Build linux binary assemblies
  hosts: zesty
  remote_user: ubuntu
  vars_files:
      - vars/common.yml
  vars:
      sources_root: "../../../../"
      result_path: "{{ outwiker_dir }}/build/{{ version }}/linux"
  environment:
      PATH: "{{ ansible_env.PATH }}:{{homedir}}/.local/bin"
  tasks:
      - name: Remove old sources directory
        file:
            path: "{{ outwiker_dir }}"
            state: "absent"

      - name: Create directories for sources
        file:
            path: "{{ outwiker_dir }}"
            state: "directory"

      - name: Upload sources
        synchronize:
            src: "{{ sources_root }}"
            dest: "{{ outwiker_dir }}"
            rsync_opts:
                - "--exclude=.git"
                - "--exclude=.ropeproject"
                - "--exclude=build"

      - name: Install Python modules
        pip: chdir={{ outwiker_dir }} requirements={{ item }} extra_args="--user"
        with_items:
            - "requirements.txt"
            - "requirements_dev.txt"

      - name: Build binary assembly
        command: fab linux_binary:{{ is_stable }}
        args:
            chdir: "{{ outwiker_dir }}"

      - name: Rename result archive
        copy:
            src: "{{ outwiker_dir }}/build/{{ version }}/linux/outwiker_linux_bin.7z"
            dest: "{{ result_path }}/outwiker_linux{{ suffix }}.7z"
            remote_src: true

      - name: Download result archive
        fetch:
            src: "{{ result_path }}/outwiker_linux{{ suffix }}.7z"
            dest: "{{ save_to }}/"
            flat: true
