---
- name: Configure virtual machine for OutWiker build
  hosts: all
  remote_user: ubuntu
  vars_files:
      - vars/common.yml
  tasks:
      - name: upgrade software
        apt: update_cache=yes upgrade=dist
        become: true

      - name: Install common software
        apt: name={{ item }}
        with_items:
          - mc
          - vim-gtk3
        become: true

      - name: Install software to build OutWiker
        apt: name={{ item }}
        with_items:
          - python3.6-dev
          - git
          - python-pip
          - python3-pip
          - python3-venv
          - python3.6-venv
          - debhelper
          - devscripts
          - p7zip-full
          - libssl-dev
          - dpkg-dev
          - build-essential
          - libjpeg-dev
          - libtiff-dev
          - libsdl1.2-dev
          # - libgstreamer-plugins-base0.10-dev
          - libnotify-dev
          - freeglut3
          - freeglut3-dev
          - libsm-dev
          - libgtk-3-dev
          - libwebkitgtk-3.0-dev
          - libgstreamer-plugins-base1.0-dev
          - libwebkit2gtk-4.0-dev
          - libsdl2-dev
        become: true

      - name: Install additional software
        apt: name={{ item }}
        with_items: "{{ additional_soft | default([]) }}"
        become: true

      - name: create directories for vagrant
        file: path={{ item }} state=directory
        with_items:
            - "{{ homedir }}/.config/mc"
            - "{{ homedir }}/projects"

      - name: copy .bashrc config file to vagrant's home
        copy: src=files/.bashrc dest={{ homedir }}/.bashrc

      - name: copy mc ini config file to vagrant's home
        copy: src=files/mc_ini dest={{ homedir }}/.config/mc/ini

      - stat: path={{ outwiker_dir }}
        register: outwiker_dir_stat

      - name: Upgrade pip
        pip:
            name: pip
            executable: pip3

